port: 8000
workerInterval: 5s

rpcs:
  - name: omniatech
    url: https://endpoints.omniatech.io/v1/eth/mainnet/public
  - name: ankr
    url: https://rpc.ankr.com/eth
  - name: blxrbdn
    url: https://eth.rpc.blxrbdn.com
  - name: 1rpc
    url: https://1rpc.io/eth
  - name: cloudflare
    url: https://cloudflare-eth.com