apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-env
  labels:
    {{- include "app.labels" . | nindent 4 }}
    hash: {{ toString .Values.env | sha256sum | trunc 32 }}
type: Opaque
data:
  "config.yaml": {{ toYaml .Values.env | b64enc }}